services:
  api_service:
      class: Core\Bundle\ServiceBundle\Service\HttpServiceGateway
      arguments: ['%servicebundle.api.protocol%', '%servicebundle.api.host%', '%servicebundle.api.endpoint%']