parameters:
    service_factory.class: Core\Bundle\ServiceBundle\Service\ServiceFactory
    service_manager.class: Core\Bundle\ServiceBundle\Service\ServiceManager
    http_client.class: Core\Bundle\ServiceBundle\Service\HttpClient

services:
    data_collector.http_data_collector:
        class: Core\Bundle\ServiceBundle\DataCollector\HttpDataCollector
        tags:
            - { name: data_collector, template: "CoreServiceBundle:collector:http", id: "http_profiling" }

    service_manager:
        class: '%service_manager.class%'
        arguments: ['%servicebundle.api.protocol%', '%servicebundle.api.host%', '%servicebundle.api.endpoint%']

    service_http_client:
        class: '%http_client.class%'
        factory_class:  '%service_factory.class%'
        factory_method: buildHttpClient
        arguments: ['@service_manager', '@session']